apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-3
      loadbalancer-type: external
  template:
    metadata:
      labels:
        app: foo-3
        loadbalancer-type: external
    spec:
      containers:
        - name: foo-3
          image: foo-3:latest
          imagePullPolicy: Never
          resources: { limits: { cpu: 300m, memory: 512Mi } }
          ports:
            - containerPort: 3000
              name: foo-3-port
