apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-3
  template:
    metadata:
      labels:
        app: foo-3
    spec:
      containers:
        - name: foo-3
          image: foo-3:latest
          imagePullPolicy: Never
          resources: { limits: { cpu: 500m, memory: 512Mi } }
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: foo-3-service
spec:
  type: NodePort
  selector:
    app: foo-3
  ports:
    - port: 3000
      targetPort: 3000
