apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-2
  template:
    metadata:
      labels:
        app: foo-2
    spec:
      containers:
        - name: foo-2
          image: foo-2:latest
          imagePullPolicy: Never
          resources: { limits: { cpu: 500m, memory: 512Mi } }
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: foo-2-service
spec:
  type: NodePort
  selector:
    app: foo-2
  ports:
    - port: 3000
      targetPort: 3000
