apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-1
      loadbalancer-type: external
  template:
    metadata:
      labels:
        app: foo-1
        loadbalancer-type: external
    spec:
      containers:
        - name: foo-1
          image: foo-1:latest
          imagePullPolicy: Never
          resources: { limits: { cpu: 300m, memory: 512Mi } }
          ports:
            - containerPort: 3000
              name: foo-1-port
