apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo-1
  template:
    metadata:
      labels:
        app: foo-1
    spec:
      containers:
        - name: foo-1
          image: foo-1:latest
          imagePullPolicy: Never
          resources: { limits: { cpu: 500m, memory: 512Mi } }
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: foo-1-service
spec:
  type: NodePort
  selector:
    app: foo-1
  ports:
    - port: 3000
      targetPort: 3000
