name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: node
        run: echo "##[set-output name=versoin;]$(cat .nvmrc)"
        id: node
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.node.outputs.version }}"
      - name: Run tests
        run: |
          npm ci
          npm run test:all --workspaces --if-present
